deploy:
  password:
    secure: gCDrRQzw5ybZPIpxFg6dr53IamUntiK8768NHZmcJz6Qjfnz2PUR963rVB3wP/+lVw3iA1U3VC1QzVnGqWx7j4DOBjm4VxwvVCK8hruWm+hq61ophOV6Eg1iC79HpM0+FqClfc+mQ+aBJ9v9OBSHqyzuC8Bm9okq3HU0NfB3UiCcDMJGBNcJ1qIUq78tA1RgvwPewd7SYjCk9av7Un1YVJ69ivBfgolJ6DXQYMFtYDE8fHJB83sVHrcLhbIZQZxD/X4O34CLrGHHKBlrb1+soeJyPwp5LgcoLzTIDNuHnQx6mvi0Iv/caBOjPgzICcWgLw0i0DpwoGnauGSKtikDmFg+yQshhvExSJF6ygL4RXcYpsiTi+N8fKqtMeX3uJRlGpHl6NBvaBF545VGpmzDA9HHcJbsjpNIwQ7VIhRnXe9kQfVdcxsfFD/v2w69r9ekFWspXxmWgVDyFuu3ivRMAHq6bSEqZ2/6/4qvceJESdCn+ID6B8IlKd24FP2hO1eeN1Ca/BmNjpxhqWGACcI5NN1kAU8mzClkB7D7JC+cS7Gj2xrn4ohTLSo82Tbjo6k7raTxC2Qoq6aasFWqGW8vqUhburmggL4tLWdT8vqMQ+pDofWdqCANt3YNxVD6atjBonOvPu35uf2H1t6kkBB8yy7RjO/XjbGWIRSN4buokBY=
  on:
    condition: $TOXENV == py35
    repo: pokey/pubmedasync
    tags: true
  provider: pypi
  distributions: sdist bdist_wheel
  user: pokey
env:
- TOXENV=py35
- TOXENV=flake8
install: pip install -U tox
language: python
python: 3.5
script: tox -e ${TOXENV}
